# Generated by Django 5.0.7 on 2024-08-06 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomDepartmentStudent',
        ),
        migrations.DeleteModel(
            name='CustomDepartmentTeacher',
        ),
        migrations.CreateModel(
            name='CustomDepartmentStudent',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('college_roll_number', models.CharField(max_length=100, unique=True)),
                ('university_roll_number', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Department Student',
                'verbose_name_plural': 'Department Students',
            },
            bases=('accounts.customuser',),
        ),
        migrations.CreateModel(
            name='CustomDepartmentTeacher',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('employee_code', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Department Teacher',
                'verbose_name_plural': 'Department Teachers',
            },
            bases=('accounts.customuser',),
        ),
    ]
