# Generated by Django 5.1.2 on 2024-10-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_is_deleted_alter_customuser_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="cnic",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
