# Generated by Django 5.1.2 on 2024-10-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjects",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
