# Generated by Django 5.0.7 on 2024-08-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_documentkeypoint_documentquiz_documentsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentkeypoint',
            name='keypoint',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='documentsummary',
            name='summary',
            field=models.TextField(),
        ),
    ]
